kind: pipeline
name: check-same-code-base

steps:
  - name: check-same-code-base
    image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
    commands:
      - make check-same-code-base

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-cli

steps:
  - name: php73-cli
    image: ghcr.io/nextcloud/continuous-integration-php7.3:latest
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-cli

steps:
  - name: php74-cli
    image: ghcr.io/nextcloud/continuous-integration-php7.4:latest
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: php73-stable19

steps:
  - name: php73-stable19
    image: ghcr.io/nextcloud/continuous-integration-php7.3:latest
    commands:
      - make test-stable19

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable19

steps:
  - name: php74-stable19
    image: ghcr.io/nextcloud/continuous-integration-php7.4:latest
    commands:
      - make test-stable19

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-stable20

steps:
  - name: php73-stable20
    image: ghcr.io/nextcloud/continuous-integration-php7.3:latest
    commands:
      - make test-stable20

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable20

steps:
  - name: php74-stable20
    image: ghcr.io/nextcloud/continuous-integration-php7.4:latest
    commands:
      - make test-stable20

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-stable21

steps:
  - name: php73-stable21
    image: ghcr.io/nextcloud/continuous-integration-php7.3:latest
    commands:
      - make test-stable21

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable21

steps:
  - name: php74-stable21
    image: ghcr.io/nextcloud/continuous-integration-php7.4:latest
    commands:
      - make test-stable21

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php80-stable21

steps:
  - name: php80-stable21
    image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
    commands:
      - make test-stable21

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-master

steps:
  - name: php74-master
    image: ghcr.io/nextcloud/continuous-integration-php7.4:latest
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php80-master

steps:
  - name: php80-master
    image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
