kind: pipeline
name: check-same-code-base

steps:
  - name: check-same-code-base
    image: nextcloudci/php8.0:php8.0-1
    commands:
      - make check-same-code-base

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-cli

steps:
  - name: php73-cli
    image: nextcloudci/php7.3:php7.3-5
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-cli

steps:
  - name: php74-cli
    image: nextcloudci/php7.4:php7.4-3
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: php73-stable19

steps:
  - name: php73-stable19
    image: nextcloudci/php7.3:php7.3-5
    commands:
      - make test-stable19

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable19

steps:
  - name: php74-stable19
    image: nextcloudci/php7.4:php7.4-3
    commands:
      - make test-stable19

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-stable20

steps:
  - name: php73-stable20
    image: nextcloudci/php7.3:php7.3-5
    commands:
      - make test-stable20

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable20

steps:
  - name: php74-stable20
    image: nextcloudci/php7.4:php7.4-3
    commands:
      - make test-stable20

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-stable21

steps:
  - name: php73-stable21
    image: nextcloudci/php7.3:php7.3-5
    commands:
      - make test-stable21

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable21

steps:
  - name: php74-stable21
    image: nextcloudci/php7.4:php7.4-3
    commands:
      - make test-stable21

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php80-stable21

steps:
  - name: php80-stable21
    image: nextcloudci/php8.0:php8.0-1
    commands:
      - make test-stable21

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php80-master

steps:
  - name: php80-master
    image: nextcloudci/php8.0:php8.0-1
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
