name: Check same code base

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  php-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.0"]

    name: check-same-code-base

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: check-same-code-base
        run: make check-same-code-base

      - name: check-updater-phar
        run: |
          make box
          ./box info -l updater.phar | grep -v "^Signature Hash" | grep -v "^  Version.php " | grep -v "^Contents: " >updater.old.txt
          make updater.phar
          ./box info -l updater.phar | grep -v "^Signature Hash" | grep -v "^  Version.php " | grep -v "^Contents: " >updater.txt
          diff updater.txt updater.old.txt
