name: Test stable

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  test-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.0", "8.1", "8.2"]
        nextcloud-versions: ["25", "26", "27"]
        exclude:
          - php-versions: "8.2"
            nextcloud-versions: "25"

    name: test-stable

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          ini-file: development

      - name: test-stable${{ matrix.nextcloud-versions }}
        run: make test-stable${{ matrix.nextcloud-versions }}

  summary:
    runs-on: ubuntu-latest
    needs: test-stable

    if: always()

    name: test-stable-summary

    steps:
      - name: Summary status
        run: if ${{ needs.test-stable.result != 'success' }}; then exit 1; fi
