name: Test cli

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  test-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.1"]

    name: test-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: test-cli
        run: make test-cli
