name: Test stable

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  test-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.0", "8.1", "8.2"]
        nextcloud-versions: ["27"]

    name: test-stable

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
        with:
          php-version: ${{ matrix.php-versions }}
          # https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test-stable${{ matrix.nextcloud-versions }}
        run: make test-stable${{ matrix.nextcloud-versions }}

  summary:
    runs-on: ubuntu-latest
    needs: test-stable

    if: always()

    name: test-stable-summary

    steps:
      - name: Summary status
        run: if ${{ needs.test-stable.result != 'success' }}; then exit 1; fi
